### ISSUE TITLE
Homework Re-submission

### ISSUE THREAD

**Issue by hegeds** [bmeaut/python_nlp_2018_spring#18]
Hello,

For me it's not quite clear the procedure of re-submission works:
Basically I can push one hw repo after the deadline (until the end of the repeat period, so till the end of this week) or is there any other administration necessary?

Thanks in advance:
Bálint

**Comment by juditacs** [comment]
I sent an email via neptun about this.
You can submit the same way, but please notify us, otherwise we won't know that you want to resubmit.
