### ISSUE TITLE
Q3 Inheritance

### ISSUE THREAD

**Issue by Dudly01** [bmeaut/python_nlp_2018_spring#3]
Hi, my question is whether I can inherit my class from list, like:
_class MutableString(list):_ or do i have to stick with _class MutableString(object):_
Thanks in advance!

**Comment by juditacs** [comment]
It's not a list, so you shouldn't inherit from list.

**Comment by gaebor** [comment]
https://stackoverflow.com/questions/9432719/python-how-can-i-inherit-from-the-built-in-list-type
